// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tchadaaevwweotpyrmrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjaGFkYWFldnd3ZW90cHlybXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTIyMzAsImV4cCI6MjA3MTY4ODIzMH0.7c0ay3C0NwTege6bS2phqdN-qRrYYjplqnuBiEYJZIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});